7 overview destenation page
GSG-CF05/Novelty-Travel-Team5 pull request #15
Opened 2022-03-21 12:31 UTC by MohamedSbaih

2022-03-21 14:00 UTC, salwasiksik submitted a review, later dismissed

2022-03-22 13:31 UTC, salwasiksik approved these changes

2022-03-22 17:46 UTC, azzsal submitted a review, later dismissed

2022-03-22 19:15 UTC, ahmedhmmad submitted a review, later dismissed

2022-03-23 07:09 UTC, sara219 requested changes

2022-03-23 07:09 UTC, sara219 commented on overview/destenation-page/destenation.html
> +              />
the image there is not shown, 

```suggestion
              <img
                src="./img/tours/tour-1-cover.jpg"
                alt="Tour 1"
                class="card__picture-img"
              />
```

2022-03-24 02:02 UTC, MohamedSbaih commented on overview/destenation-page/destenation.html
> +              />
Done

2022-03-24 07:48 UTC, sara219 approved these changes

2022-03-24 09:03 UTC, ahmedhmmad approved these changes

2022-03-24 09:11 UTC, salwasiksik approved these changes

2022-03-24 10:54 UTC, azzsal approved these changes

2022-03-24 10:54 UTC, merged