Add desktop version of landing page relates #19
GSG-CF05/Novelty-Travel-Team5 pull request #20
Opened 2022-03-22 00:02 UTC by ahmedhmmad

2022-03-22 06:25 UTC, salwasiksik submitted a review, later dismissed

2022-03-23 07:15 UTC, sara219 requested changes
This is how it looks on the big screen, maybe you can put it in the center of the page, it will look more acceptable

<img width="1438" alt="Screen Shot 2022-03-23 at 9 14 05 AM" src="https://user-images.githubusercontent.com/47992412/159643815-217d1d42-2939-4c14-9884-58aabce8d5cc.png">

2022-03-24 09:10 UTC, sara219 approved these changes

2022-03-24 09:11 UTC, salwasiksik approved these changes

2022-03-24 09:13 UTC, merged