create location page mobile version, t2h
GSG-CF05/Novelty-Travel-Team5 pull request #22
Opened 2022-03-22 12:51 UTC by salwasiksik

relates #21

2022-03-22 13:25 UTC, ahmedhmmad approved these changes, later dismissed

2022-03-23 03:42 UTC, MohamedSbaih reviewed
Add this file inside the overview folder

2022-03-23 20:03 UTC, azzsal approved these changes, later dismissed

2022-03-24 10:04 UTC, Yousef-Dall requested changes

2022-03-24 10:04 UTC, Yousef-Dall commented on locations-page/locations.html
> +  <img class="sec-pic" src="../assets/images/Location-page/Rectangle 4.svg" alt="sanfrancisco">
push the image

2022-03-24 10:04 UTC, Yousef-Dall commented on locations-page/locations.html
> +  <button><p>Explore</p></button>
add the link to the destination page

2022-03-24 10:04 UTC, Yousef-Dall commented on locations-page/locations.html
> +  <img class="thrid-pic" src="../assets/images/Location-page/Rectangle 6.svg" alt="paris" >
push the image

2022-03-24 10:04 UTC, Yousef-Dall commented on locations-page/locations.html
> +      <img src="../assets/images/Location-page/Group 26.svg" alt="Berlin">
push the image

2022-03-24 14:13 UTC, ahmedhmmad approved these changes

2022-03-24 14:23 UTC, azzsal approved these changes

2022-03-24 15:29 UTC, Yousef-Dall approved these changes

2022-03-24 15:29 UTC, merged

2022-03-24 15:29 UTC, MohamedSbaih approved these changes